services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    # other service1 configurations
  
  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    # other service2 configurations
